### ISSUE TITLE
How to test it?

### ISSUE THREAD

**Issue by dewiweb** [bitfocus/companion-module-analogway-awj#1]
Hello,
We've got an EIKOS4K and want to test your module.
How can we integrate it in our current companion install?
Regards

**Comment by dnmeid** [comment]
Come on, I've uploaded this a few hours ago. It needs a little more debugging and then it will be included in betas / release.
Please don't use this issues section for general questions and discussion.

**Comment by dnmeid** [comment]
It is in the latest beta now. Please feel free to test.
