### ISSUE TITLE
Memories or Screen Selections don't follow in Web RCS

### ISSUE THREAD

**Issue by ianmcfancypants** [bitfocus/companion-module-analogway-awj#18]
When selecting a memory in companion, the screen selection doesn't follow as it does when you load the memory within RCS.  It recalls the memory, but it puts it in whatever screen is selected in RCS instead of what's saved in the memory.

Also in the screens presets, the screen selection doesn't seem to do anything in RCS.

Using Aquilon RS6 with Firmware 4.1.38 (Newer Firmware currently has an input bug, at least on the RS6 frame)
Companion:  v3.4.0+7195-main-cc20002d

**Comment by dnmeid** [comment]
I can't reproduce your issue. Most probably you have not turned on 'sync selection' in your WebRCS client. Please read the manual.
Additionally I can't follow your issue because there are different types of memories in WebRCS and Companion and you don't specify which type of memory you are referring to.

**Comment by ianmcfancypants** [comment]
Undersood.

I was in the middle of a big show and ended up just mouse-clicking instead.  My best guess is that it had something to do with an older firmware on the RS6.  That unit is so new that firmware wasn’t stable for it yet.  I did have sync turned on.  And it was the main memories I was trying to pull up.  Most buttons became unresponsive in Companion… which really makes me think that it’s due to the pre-production nature of the unit, not Companion.  I’m no longer around the rig so can’t test any further.

~Ian
