### ISSUE TITLE
GPO not working on Livepremier 4.2.17

### ISSUE THREAD

**Issue by robertskiba** [bitfocus/companion-module-analogway-awj#23]
Hi Dorian,

I just checked with my RS2 and your AWJ module 2.4.1: 

Currently, the GPO feedback for a manual GPO is working. 

Also, the command "set GPO" is not available. 

I don't know if thats just missing on my specific model or if it's a problem with all Livepremier devices. 

Could you please check that?

**Comment by dnmeid** [comment]
Which version of LivePremier?

**Comment by robertskiba** [comment]
Always the most current!

**Comment by dnmeid** [comment]
That is not an answer, please give me the version number.

**Comment by robertskiba** [comment]
Sorry, it is 4.2.17

**Comment by dnmeid** [comment]
You can write a letter of thanks to our friends at AnalogWay. Among the hundreds of unnecessary changes between v3 and v4 is also this one: they renamed the internal path for the GPIO-interface from `device/gpio` to `device/gpios`.
I really hope the guy responsible for all that mess has been fired or will be. I really hope, but I'm afraid they rather promote him.

I'm working on an update.

**Comment by dnmeid** [comment]
@robertskiba Can you please check if the GPI and GPO actions and feedbacks are working with this version: 
[pkg.zip](https://github.com/user-attachments/files/17175843/pkg.zip)

**Comment by robertskiba** [comment]
Hi Dorian, 

I just had time to check. 

1. Turning GPO on/off or toggle doesn't work
2. feedbacks only show the current state when reconnecting/enabling the module. No "live-update".
3. compared to the 2.4.1, the option to set gpo state is correctly displayed.

Log: Connected to Aquilon RS2, S/N: <hidden>, fw 4.2.17

If you want to try yourself on a live system, just contact me for teamviewer credentials.

**Comment by dnmeid** [comment]
Found another typo. Can you please check the attached version. Please check also the GPI as I can't do that with the simulator.
And another question: in the qouted log line, did you delete the S/N by hand or is it not logged? Actually there should be the serial number of the device.
[pkg.zip](https://github.com/user-attachments/files/17190230/pkg.zip)

**Comment by robertskiba** [comment]
Hi Dorian,

so I did a full test of all 8 GPO (turning them on, off or toggle them on/off)

Now most things work

- GPO 1 to 7 work, GPO8 doesn't work at all (no feedback, no commands). Maybe there's still some typo/bug?
- GPI 1 feedback also works fine.

BTW I deleted the serial by hand, it's the correct serial of my device.

**Comment by robertskiba** [comment]
Little addition: 
GPI 2 doesn't work either! No feedback at all!

**Comment by robertskiba** [comment]
One more addition: 
I also tested the correct feedback behaviour if GPO are in Tally mode. It also works great, but due to too many possible screen combinations, I only tested it with S1. Is there any special combinations i could test? Maybe like S32?

**Comment by dnmeid** [comment]
Thank you, found also the last one.
No need to test other screen combinations as I read only the state, no matter where it comes from.

Closed in b6aa093e7b8e1daf5dca1eebe5e9404276151edd

**Comment by robertskiba** [comment]
Just a confirmation: With the current beta (3.5.0+7430), everything about the GPIOs works great now!
