### ISSUE TITLE
Cannot get it to connect to LivePremier Simulator

### ISSUE THREAD

**Issue by SloppyButDecent** [bitfocus/companion-module-analogway-awj#24]
Unlike the other Companion module for LivePremier, I am unable to get this one to connect to the simulator session that I have open to test buttons and flows.

**Comment by dnmeid** [comment]
It seems that is a problem on your side. I can connect without problems to the simulator (all versions).
Do you use the correct IP and port number?

**Comment by SloppyButDecent** [comment]
I’ve used 127.0.0.1:10606 and 192.168.2.140:10606, the latter of which is the one that is auto populated when the connection is added.

**Comment by PhillPower** [comment]
try 3000 instead of 10606

**Comment by SloppyButDecent** [comment]
I’ve done that as well with no luck. Happens on both PC and Mac.

**Comment by dnmeid** [comment]
Can you successfully connect to WebRCS with a browser from the machine where Companion is running on? If yes, use the same URL that you use in the browser. Including the protocol, the ip or hostname and the port.
That is also written in the help page.

**Comment by SloppyButDecent** [comment]
Updating to the most recent companion fixed the issue.  I was 1 version behind.
