### ISSUE TITLE
Select layer source does not work with Aquilion since 4.0

### ISSUE THREAD

**Issue by arlon666** [bitfocus/companion-module-analogway-awj#26]
Hey Dorian,
Great job updating the module!!! The only issue i have had though is the select layer source command. I often use this for routing sources to my Aux/DSM feeds.  Whenever i use this, it works in the RCS interface but not on the actual hardware. I believe this worked in the first 4.0.254 release but not in any version since then.

**Comment by dnmeid** [comment]
Can you please tell me the device you are using, the version of the device, the version of the module.
Then please describe exactly what is not working.
I don't have a real device here, so I can only track bugs with the simulator and that is not up to date but maybe we get it sorted.

**Comment by arlon666** [comment]
> Can you please tell me the device you are using, the version of the device, the version of the module. Then please describe exactly what is not working. I don't have a real device here, so I can only track bugs with the simulator and that is not up to date but maybe we get it sorted.

Sure, here is what i am using

Aquilon RS2  V4.2.17
Companion V3.4.2
AWJ module v2.4.2

I create a button and add the 
AWJdevice: Select Layer Source
Method : Target specified layer
Screen/Aux : A1
Preset: Program
Layer A1: Layer 1
Aux Layer Source: (choose my input)

This works in the simulator and in the RSC when connect to the RS2.  But no response on the hardware.

**Comment by dnmeid** [comment]
Ok, I think I found the bug. Can you please test the attached version: [pkg.zip](https://github.com/user-attachments/files/17399579/pkg.zip)
While you're at it, can you please also test the wakeup/shutdown action. There is another bugreport about it and then I could fix both problems in one go.

**Comment by arlon666** [comment]
Sure i can test them for you, I just need a refresher of how to use the file you gave me.

**Comment by dnmeid** [comment]
> Sure i can test them for you, I just need a refresher of how to use the file you gave me.

https://github.com/bitfocus/companion/wiki/How-to-use-a-module-that-is-not-included-in-Companion-build

**Comment by arlon666** [comment]
ok i followed the instructions but I don't see the developers module. I checked the log and switched to debug mode.

                  log: You can view older logs in the configuration folder
24.10.16 16:35:38 Log/Controller: Application starting
24.10.16 16:35:38 Registry: Build 3.4.2+7335-stable-fc3fe2f0
24.10.16 16:35:38 Registry: configuration directory: C:\Users\TB\AppData\Roaming\companion\v3.4
24.10.16 16:35:38 Log/Controller: Sentry error reporting configured
24.10.16 16:35:38 Graphics/Controller: Render worker created
24.10.16 16:35:38 Graphics/Controller: Render worker created
24.10.16 16:35:38 Graphics/Controller: Loading fonts
24.10.16 16:35:38 Graphics/Controller: Fonts loaded
24.10.16 16:35:38 Service/BonjourDiscovery: Listening for Bonjour messages
24.10.16 16:35:38 Graphics/Controller: Render worker created
24.10.16 16:35:38 Graphics/Controller: Render worker created
24.10.16 16:35:38 Graphics/Controller: Render worker created
24.10.16 16:35:38 Graphics/Controller: Render worker created
24.10.16 16:35:39 Instance/Modules: Looking for extra modules in: C:\Users\TB\Desktop\companion-module-dev\companion
24.10.16 16:35:39 Instance/Modules: Found 0 extra modules
24.10.16 16:35:39 UI/Server: new url: http://127.0.0.1:8000/

**Comment by dnmeid** [comment]
if you unzip, you'll have a folder named "pkg". That is the module. You need the whole folder, not just the content.
You put that "pkg"-folder into the folder that you assigned to be your local-dev folder, apparently C:\Users\TB\Desktop\companion-module-dev\companion

**Comment by arlon666** [comment]
ok i got it running now.  Yes this fixed both bugs.  So the select layer source is good and the power on/off is now working.  Thank you :) Let me know if you need me to test anything else for you.  My name is Tim Burke and I am a certified Live Premier Certified Trainer. I have an RS2, zenith 200 and pulse 4k so I can test them all for you.  My email is tburke@avdusa.com
