### ISSUE TITLE
AUX feedback not functional with 4.2.17

### ISSUE THREAD

**Issue by robertskiba** [bitfocus/companion-module-analogway-awj#27]
Hi Dorian,

I don't know if you have already known about it, but the feedbacks on AUX Screens don't work at the moment at least with the following versions:

Aquilon Firmware 4.2.17

Companion AWJ Module 2.4.2

I tried it on a C+ (24IN/16Out) and on a RS2 (16IN/16OOUT), but it's perfectly working when doing a manual JSON feedback. So I guess it's just a simple JSON matter.

**Comment by robertskiba** [comment]
Of course! 

I'm using the screen preset feedback, select an AUX-Screen and the preset I want to get the feedback for. It doesn't matter if I choose preview, program or any, it doesn't work at all. "is modified" doesn't matter also. 

Here's the path returned by custom feedback learning

DeviceObject/$screenAuxGroup/@items/A1/status/@props/transition

and here the json for 

DeviceObject/$screenAuxGroup/@items/A1

{"control":{"pp":{"copyMode":false,"tbarPosition":0,"takeUpTime":10,"takeDownTime":10,"presetUp":"B","presetDown":"A","presetPrevious":"C","xTake":false,"xTakeUp":true,"xTakeDown":true,"xTakeAbort":false,"xCut":false,"xStepBack":false,"xCopyProgramToPreview":false}},"status":{"pp":{"isUsed":true,"transition":"AT_DOWN","take":"OFF","tbarPosition":0,"isTbarPositionValid":true}}}

Hope something helps you to find the bug.

**Comment by dnmeid** [comment]
There is no "screen preset" feedback?

**Comment by robertskiba** [comment]
Hi Dorian,

you are right, of course! I meant the screen memory. 

It's currently not working at all with aux screens, but it works fine with 'regular' screens.

**Comment by dnmeid** [comment]
Found one bug, another one of the annoying inconsistencies of the new AW device model. Sometimes they use aux, sometimes auxscreen, sometimes auxiliary, sometimes auxiliaryScreen, in one place even screenAux. It is so stupid.
Please check, if this version is working with screens and auxscreens: [pkg.zip](https://github.com/user-attachments/files/17414365/pkg.zip)

**Comment by robertskiba** [comment]
As far as I could test it, it works great know with AUX and SCREEN memories feedback.
