### ISSUE TITLE
Can´t connect to teh simulator

### ISSUE THREAD

**Issue by Techstenger** [bitfocus/companion-module-analogway-awj#3]
HI
I tried to use both the simulator and companion on the same computer but without any luck. Can you confirm this is woorking or am i doing anything wrong?

Best Regards
Niels

**Comment by dnmeid** [comment]
I can confirm that this is working. You probably are doing something wrong.
The real machine is listening on TCP/IP port 80, which is the default and doesn't need to be added to the device address.
The simulator can't listen on ports below 1024, the default is 3000.
You have to add the port to your device address like: 127.0.0.1:3000.
Just enter the address exactly like you do in your browser to reach the WebRCS.
