### ISSUE TITLE
Routing Dante Inputs to Costum Channels

### ISSUE THREAD

**Issue by relaisstation** [bitfocus/companion-module-analogway-awj#8]
It is not possible to route the Dante inputs to the Costum channels (neither with Audio Chanell nor with Block).
Analog Way Zenith 100 firmware 1.0.26

**Comment by dnmeid** [comment]
Which version of the module?

**Comment by relaisstation** [comment]
In both versions.
Both in the current stable release and in the beta release.

**Comment by dnmeid** [comment]
Found the bug and solved in [3e899be](https://github.com/bitfocus/companion-module-analogway-awj/commit/3e899bef6ab35cf1d703dbfcb1da98ee1f4af57b)
